# ======================================================================
# 🛠️ Composite GitHub Action: Semantic Release Protected Branch
#
# ✅ Description:
# This composite action performs semantic-release steps for protected branches using a GitHub App.
#
# 📦 Inputs:
#   - GITHUB_TOKEN: Token for GitHub API access (App or PAT)
#   - USER_ID: GitHub App user ID
#   - APP_SLUG: GitHub App slug
#   - PRIVATE_KEY: Private key for the GitHub App
#
# ======================================================================
# 🧩 Usage Example & Setup Instructions
#
# 1️⃣ Additional setup:
#   - See the following gist for detailed instructions:
#     https://gist.github.com/0xernesto/a8065cce55940e6ccc523664a87ee9bc
#   - You must set up a GitHub App and add the following repository secrets:
#       RELEASER_ID:            The App ID of your GitHub App
#       RELEASER_PRIVATE_KEY:   The private key for your GitHub App
#       NPM_TOKEN:              Your npm publish token
#   - For GitHub App setup and secret configuration, follow the steps in the gist above.
#
# 2️⃣ Example workflow usage:
#
# ```yaml
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Generate bot app token
#         id: generate_token
#         uses: actions/create-github-app-token@v2
#         with:
#           app-id: ${{ secrets.RELEASER_ID }}
#           private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}
#
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#           token: ${{ steps.generate_token.outputs.token }}
#
#       - name: Setup project
#         uses: ./.github/actions/setup-project
#         with:
#           registry-url: 'https://registry.npmjs.org'
#
#       - uses: pixpilot/github/actions/semantic-release-protected-branch@main
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           USER_ID: ${{ secrets.RELEASER_ID }}
#           APP_SLUG: ${{ secrets.RELEASER_APP_SLUG }}
#           PRIVATE_KEY: ${{ secrets.RELEASER_PRIVATE_KEY }}
# ```
# ======================================================================

name: Semantic Release Protected Branch
description: Composite action to run semantic-release for protected branches using a GitHub App.

inputs:
  GITHUB_TOKEN:
    description: Token for GitHub API access (App or PAT)
    required: true
  USER_ID:
    description: GitHub App user ID
    required: true
  APP_SLUG:
    description: GitHub App slug
    required: true
  PRIVATE_KEY:
    description: Private key for the GitHub App
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git user
      run: |
        git config --global user.name "${{ inputs.APP_SLUG }}[bot]"
        git config --global user.email "${{ inputs.USER_ID }}+${{ inputs.APP_SLUG }}[bot]@users.noreply.github.com"
      shell: bash

    - name: Release with semantic-release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ inputs.PRIVATE_KEY }}
      run: pnpm run release
      shell: bash
