# ======================================================================
# 🛠️ Composite GitHub Action: Semantic Release Protected Branch
#
# ✅ Description:
# This composite action performs semantic-release steps for protected branches using a GitHub App.
#
# 📦 Inputs:
#   - GITHUB_TOKEN: Token for GitHub API access (App or PAT)
#   - USER_ID: GitHub App user ID
#   - APP_SLUG: GitHub App slug
#   - NPM_TOKEN: NPM token for publishing packages
#
# ======================================================================
# 🔑 GitHub App Setup & Required Secrets
#
# To use this action, you must set up a GitHub App and configure repository secrets:
# - See the following gist for detailed instructions on creating a GitHub App:
#   https://gist.github.com/0xernesto/a8065cce55940e6ccc523664a87ee9bc
# - Add these repository secrets:
#     RELEASER_ID:            The App ID of your GitHub App
#     RELEASER_PRIVATE_KEY:   The private key for your GitHub App
#     NPM_TOKEN:              Your npm publish token
# - For GitHub App setup and secret configuration, follow the steps in the gist above.
#
# ======================================================================
# 🧩 Usage Example
#
# .github/workflows/release.yml
#
# name: Release Package
#
# on:
#   push:
#     branches:
#       - main
#       - next
#   workflow_dispatch:
#
# jobs:
#   ci:
#     name: Run CI Checks
#     uses: ./.github/workflows/ci.yml
#
#   release:
#     runs-on: ubuntu-latest
#     needs: ci
#     steps:
#       - name: Generate bot app token
#         id: generate_token
#         uses: actions/create-github-app-token@v2
#         with:
#           app-id: ${{ secrets.RELEASER_ID }}
#           private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}
#
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#           token: ${{ steps.generate_token.outputs.token }}
#
#       - name: Setup project
#         uses: ./.github/actions/setup-project
#         with:
#           registry-url: 'https://registry.npmjs.org'
#
#       - uses: pixpilot/github/actions/semantic-release-protected-branch@main
#         with:
#           GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
#           USER_ID: ${{ steps.generate_token.outputs.user-id }}
#           APP_SLUG: ${{ steps.generate_token.outputs.app-slug }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
# ======================================================================

name: Semantic Release Protected Branch
description: Composite action to run semantic-release for protected branches using a GitHub App.

inputs:
  GITHUB_TOKEN:
    description: Token for GitHub API access (App or PAT).
    required: true
  USER_ID:
    description: GitHub App user ID
    required: true
  APP_SLUG:
    description: GitHub App slug
    required: true
  NPM_TOKEN:
    description: NPM token for publishing packages
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git user
      run: |
        git config --global user.name "${{ inputs.APP_SLUG }}[bot]"
        git config --global user.email "${{ inputs.USER_ID }}+${{ inputs.APP_SLUG }}[bot]@users.noreply.github.com"
      shell: bash

    - name: Release with semantic-release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
      run: pnpm run release
      shell: bash
